### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by KevinZonda** [liaosunny123/SoruxBot#4]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Version**
Please tell us the version of the wrapper that you are using.

**Provider About**
Please tell us what provider that you are using. If it is not the built-in provider,please connect its own author instead of here if you ensuring that it is not the bug of the project.

**Additional context**

**Comment by liaosunny123** [comment]
https://github.com/SoruxBot/SoruxBot/commit/de269a198b32005176e031e816fea1142312b43f

**Comment by KevinZonda** [comment]
NOT FINISHED!

**Comment by liaosunny123** [comment]
Fix Another https://github.com/SoruxBot/SoruxBot/commit/2187efd3e0f3c5dc95ef36c5048b4648e6f1a630

**Comment by KevinZonda** [comment]
I hv used a `$"X{sha1(content)}"` to prevent injection. I hv no idea how to prevent hash collision.

65ae8dc6d494955f5240479fd80f4d607eb52a1b
